services:
  - type: web
    name: dogpad-backend
    runtime: node
    repo: https://github.com/archeryfox/dogpad666
    plan: free
    envVars:
      - key: LOG_SERVER_URL
        sync: false
      - key: BACKUP_SERVER_URL
        sync: false
      - key: DB_PATH
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    region: frankfurt
    buildCommand: bun install
    startCommand: bun run app.js
    healthCheckPath: /health
    ports:
      - 8081
    previews:
      generation: manual

  - type: web
    name: prisma-studio
    runtime: node
    repo: https://github.com/archeryfox/dogpad666
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: true
    region: frankfurt
    buildCommand: bun install
    startCommand: npx prisma studio --port 5555
    ports:
      - 5555
    healthCheckPath: /health
    previews:
      generation: manual
