@startuml

entity "Пользователь" as User {
  * Имя
  * Электронная почта
  * Пароль
  * Роль
  * Организуемые мероприятия
  * Подписки
}

entity "Роль" as Role {
  * Название
  * Пользователи
}

entity "Мероприятие" as Event {
  * Название
  * Описание
  * Дата
  * Местоположение
  * Организатор
  * Подписки
  * Спикеры
  * Категории
  * Площадка
}

entity "Подписка" as Subscription {
  * Пользователь
  * Мероприятие
  * Дата подписки
}

entity "Спикер" as Speaker {
  * Имя
  * Биография
  * Участие в мероприятиях
}

entity "Категория" as Category {
  * Название
  * Мероприятия
}

entity "Площадка" as Venue {
  * Название
  * Адрес
  * Вместимость
  * Мероприятия
}

User --|> Role : "Роль"
User --|> Event : "Организатор"
User --> Subscription : "Подписки"
Subscription --> User : "Пользователь"
Subscription --> Event : "Мероприятие"
Event --> Speaker : "Спикеры"
Event --> Category : "Категории"
Event --> Venue : "Площадка"
Speaker --> Event : "Участие в мероприятиях"
Category --> Event : "Категория"
Venue --> Event : "Проводимые мероприятия"

@enduml
